### ISSUE TITLE
Support Singularity successor Apptainer (`Cannot enable more than one container engine -- Choose either one of: singularity, apptainer`)

### ISSUE THREAD

**Issue by paulmenzel** [ciccalab/SIMPLI#8]
https://github.com/ciccalab/SIMPLI/blob/09e3bd432a247544d74154c90cf4bb46a2a32a08/nextflow.config#L1-L3

[Apptainer](https://apptainer.org/) is the successor of Singularity.

```
$ curl https://singularity.hpcng.org/
<!DOCTYPE html>
<html>             
    <head>
        <meta http-equiv="refresh" content="0; url='https://apptainer.org/index.html'" />
    </head>
    <body>
        <h2 style="text-align: center; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">This page has been moved to our new domain! ( apptainer.org ). Please wait well we redirect you. </h2>
[…]
```

Nextflow supports a variety of container runtimes, including Apptainer. It’d be nice, if SIMPLI would support it too and not hardcode Singularity.

    $ ./launch.sh run https://github.com/ciccalab/SIMPLI -profile test -with-apptainer /dev/shm/nextflow/singularity/containers/simpli_imaging-default-simpli_imctools_stardist-test.img
    N E X T F L O W  ~  version 23.02.1-edge
    Launching `https://github.com/ciccalab/SIMPLI` [condescending_dalembert] DSL2 - revision: 09e3bd432a [master]
    Cannot enable more than one container engine -- Choose either one of: singularity, apptainer

**Comment by MicheleBortol** [comment]
Hi @paulmenzel,

Thank you for pointing this out it is a good suggestion. I updated the `nextflow.config` file to support both apptainer and singularity. See this [commit](https://github.com/ciccalab/SIMPLI/commit/e9fc4f12dcb070b1761f3945229aa0c8dcf3bbc4. To run the pipeline now you need to specify either `apptainer` or `singularity` as a profile. For instance:
+ `nextflow run ciccalab/SIMPLI -profile test,singularity`
+ `nextflow run ciccalab/SIMPLI -profile test,apptainer`
Using the `-with--aptainer` option is not possible because SIMPLI depends on 3 separate containers.

Please let me know if this works for you.

Best wishes

Michele
